#!/bin/sh

set -o errexit

cd "${0%/*}"

VULKAN_SDK_VERSION=1.4.313.0
GLSLANG_VERSION=15.3.0

# === Linux ===
VULKAN_SDK_FILENAME=vulkansdk-linux-x86_64-$VULKAN_SDK_VERSION.tar.xz
curl -JOL https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VERSION/linux/$VULKAN_SDK_FILENAME
EXE_DIR=$VULKAN_SDK_VERSION/x86_64/bin
tar --strip-components=3 -xf $VULKAN_SDK_FILENAME $EXE_DIR/glslang $EXE_DIR/glslangValidator $EXE_DIR/spirv-opt $EXE_DIR/spirv-remap
tar -cJf glslang-$GLSLANG_VERSION-Linux.tar.xz glslang glslangValidator spirv-opt spirv-remap
rm $VULKAN_SDK_FILENAME glslang glslangValidator spirv-opt spirv-remap

# === macOS ===
VULKAN_SDK_FILENAME=vulkansdk-macos-$VULKAN_SDK_VERSION.zip
curl -JOL https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VERSION/mac/$VULKAN_SDK_FILENAME
unzip -j $VULKAN_SDK_FILENAME vulkansdk-macOS-$VULKAN_SDK_VERSION.app/Contents/Resources/installer.dat
./extract_7z.py installer.dat
tar --strip-components=2 -xf vulkan-sdk.7z macOS/bin/glslang macOS/bin/glslangValidator macOS/bin/spirv-opt macOS/bin/spirv-remap
tar -cJf glslang-$GLSLANG_VERSION-macOS.tar.xz glslang glslangValidator spirv-opt spirv-remap
rm $VULKAN_SDK_FILENAME installer.dat vulkan-sdk.7z glslang glslangValidator spirv-opt spirv-remap

# === Windows ===
VULKAN_SDK_FILENAME=vulkansdk-windows-X64-$VULKAN_SDK_VERSION.exe
curl -JOL https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VERSION/windows/$VULKAN_SDK_FILENAME
./extract_7z.py $VULKAN_SDK_FILENAME
tar --strip-components=1 -xf vulkan-sdk.7z Bin/glslangValidator.exe Bin/spirv-opt.exe Bin/spirv-remap.exe
tar -cJf glslang-$GLSLANG_VERSION-Windows.tar.xz glslangValidator.exe spirv-opt.exe spirv-remap.exe
rm $VULKAN_SDK_FILENAME vulkan-sdk.7z glslangValidator.exe spirv-opt.exe spirv-remap.exe
