find_path(OPUS_INCLUDE_DIR opusfile.h PATH_SUFFIXES opus)
find_library(OPUS_LIBRARY opus)
find_library(OPUSFILE_LIBRARY opusfile)
mark_as_advanced(OPUS_INCLUDE_DIR OPUS_LIBRARY OPUSFILE_LIBRARY)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Opus DEFAULT_MSG OPUSFILE_LIBRARY OPUS_LIBRARY OPUS_INCLUDE_DIR)
