name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.target }} - ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        target: ["quakespasm", "quakespasm-spiked", "vkquake"]
        config:
        - {
            name: "Linux Clang",
            os: ubuntu-20.04,
            extra_options: "-DCMAKE_C_COMPILER=clang"
          }
        - {
            name: "Linux GCC",
            os: ubuntu-20.04
          }
        - {
            name: "macOS",
            os: macos-11
          }
        - {
            name: "MSVC 32-bit",
            os: windows-2019,
            extra_options: "-A Win32"
          }
        - {
            name: "MSVC 64-bit",
            os: windows-2019,
            extra_options: "-A x64"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Checkout Source Code
      shell: bash
      run: |
        git submodule update --init -- src/${{ matrix.target }}

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == 'Linux' ]]; then
          sudo apt update && sudo apt install libflac-dev libmikmod-dev libmpg123-dev libopusfile-dev libsdl2-dev libvorbis-dev libvulkan-dev libxmp-dev zlib1g-dev
        elif [[ "${{ runner.os }}" == 'macOS' ]]; then
          if [[ "${{ matrix.target }}" == 'vkquake' ]]; then
            # Install Vulkan headers
            # Do not use Homebrew package in order to match with loader's version
            curl -JOL https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/sdk-1.2.189.0.tar.gz
            tar -xf Vulkan-Headers-sdk-1.2.189.0.tar.gz
            cd Vulkan-Headers-sdk-1.2.189.0
            cmake .
            cmake --build .
            sudo cmake --install .

            # Install Vulkan loader
            curl -JOL https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/sdk-1.2.189.0.tar.gz
            tar -xf Vulkan-Loader-sdk-1.2.189.0.tar.gz
            cd Vulkan-Loader-sdk-1.2.189.0
            cmake .
            cmake --build . --parallel 3
            sudo cmake --install .
          fi

          brew install flac libmikmod libvorbis libxmp mpg123 opusfile sdl2
        fi

    - name: Configure
      shell: bash
      run: |
        cmake -B build -DQUAKE_TARGET=${{ matrix.target }} ${{ matrix.config.extra_options }} .

    - name: Build
      shell: bash
      run: |
        export MAKEFLAGS=--keep-going
        cmake --build build --config Release --parallel 3

    - name: List Build Directory
      if: always()
      shell: bash
      run: |
        git status
        ls -lR build
